backend:
  name: github
  repo: HyperReal256/your-repo-name  # replace this with your GitHub username/repo
  branch: main  # or master if your default branch is master

media_folder: "images/uploads"  # where uploaded files will be stored in the repo
public_folder: "/images/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
